services:
  - type: web
    name: score-bot
    env: python
    region: oregon        # یا singapore یا هر جا که می‌خوای
    plan: free            # رایگان
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true

    # متغیرهای محیطی (اینجا جدا تعریف می‌شه)
    envVars:
      PYTHON_VERSION: "3.11.6"